export const LOGIN_LOGGED_IN = "LOGIN_LOGGED_IN";
export const LOGIN_LOGGED_OUT = "LOGIN_LOGGED_OUT";
export const LOGIN_LOGON_FAILURE = "LOGIN_LOGON_FAILURE";
export const LOGIN_LOGON_REQUEST = "LOGIN_LOGON_REQUEST";

export const CHANGE_CONTACT = "CHANGE_CONTACT";
export const CHANGE_CONTACT_REQUEST = "CHANGE_CONTACT_REQUEST";
export const CHANGE_CONTACT_FAILURE = "CHANGE_CONTACT_FAILURE";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const DELETE_CONTACT_REQUEST = "DELETE_CONTACT_REQUEST";
export const DELETE_CONTACT_FAILURE = "DELETE_CONTACT_FAILURE";
export const CREATE_CONTACT = "CREATE_CONTACT";
export const CREATE_CONTACT_REQUEST = "CREATE_CONTACT_REQUEST";
export const CREATE_CONTACT_FAILURE = "CREATE_CONTACT_FAILURE";
export const GET_CONTACTS = "GET_CONTACTS";
export const GET_CONTACTS_REQUEST = "GET_CONTACTS_REQUEST";
export const GET_CONTACTS_FAILURE = "GET_CONTACTS_FAILURE";

export const CHANGE_THEME = "CHANGE_THEME";